### ISSUE TITLE
Dataset creditcard.csv

### ISSUE THREAD

**Issue by DrCard** [ellisvalentiner/credit-card-fraud#5]
i would like to understand what the numbers in the csv file mean as i can only see time amount and class.

i would like to add or modify the transaction results to integrate with the data i have collected and add geo ip and device fingerprint to the equation 

thank you so much

**Comment by ellisvalentiner** [comment]
@DrCard I did not collect data, so unfortunately I can't tell you much about the other fields. They were intentionally obfuscated by the researchers for the sake of privacy.
